version: 2.1
​
jobs:
  print-a-message:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run: yarn version
​
workflows:
  my-workflow:
    jobs:
      - print-a-message