version: 2.1

executors:
  my-executor:
    docker:
      - image: cimg/node:18.4.0
    working_directory: /

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run: yarn version
      - run: yarn install
      - run: yarn build
      - persist_to_workspace:
          root: workspace
          paths:
            - echo-output
  test:
    executor: my-executor
    steps:
      - attach_workspace:
          at: /workspace
      - run: yarn test

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
