version: 2.1

orbs:
  node: circleci/node@5.0.2

executors:
  my-executor:
    docker:
      - image: cimg/node:18.4.0

jobs:
  build_and_test:
    executor: my-executor
    steps:
      - checkout
      - run: echo "Build start on `date`"
      - run: yarn version
      - run: yarn install
      - run: yarn build
      - run: echo "Test start on `date`"
      - run: yarn test

workflows:
  build_and_test:
    jobs:
      - build_and_test
