version: 2.1

orbs:
  node: circleci/node@5.0.2

executors:
  my-executor:
    docker:
      - image: cimg/node:18.4.0

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run: echo "Build start on `date`"
      - run: yarn version
      - run: yarn install
      - run: yarn build
      - run: mkdir -p workspace
      - run: echo "Hello, world!" > workspace/echo-output
      - persist_to_workspace:
          root: workspace
          paths:
            - echo-output
  test:
    executor: my-executor
    steps:
      - attach_workspace:
          at: ./workspace
      - run: echo "`cat /workspace/echo-output`"
      - run: echo "Test start on `date`"
      - run: yarn test

workflows:
  build_and_test:
    jobs:
      - need-approval:
          type: approval
          filters:
            branches:
              only:
                - beta
      - build:
          requires:
            - need-approval
      - test:
          requires:
            - build
