version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - checkout
      - run: yarn version
      - run: echo ${MY_ENV_VAR}

workflows:
  build_only:
    jobs:
      - build:
          context:
            - my-context
