version: 2.1

orbs:
  node: circleci/node@5.0.2

executors:
  my-executor:
    docker:
      - image: cimg/node:18.4.0

jobs:
  build_and_test_and_deploy:
    executor: my-executor
    steps:
      - checkout
      - run: echo "Build start on `date`"
      - run: yarn install
      - run: yarn build
      - run: echo "Test start on `date`"
      - run: yarn test
      -
      - add_ssh_keys:
          fingerprints:
            - '10:3e:e4:71:0c:da:36:9c:b2:4c:82:f3:38:b3:ef:9b'
      - run: npm install -g --silent gh-pages@2.0.1
      - deploy:
          name: Deploy next js app
          command: |
            git config --global user.name "fjtiaratsalsa"
            git config --global user.email "tiara@fivejack.com"
      - run: echo "Deploy start on `date`"
      - run: yarn deploy
workflows:
  build_and_test_and_deploy:
    jobs:
      - need-approval:
          type: approval
          filters:
            branches:
              only:
                - beta
      - build_and_test_and_deploy:
          requires:
            - need-approval
