version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - checkout
      - run: yarn version
      - run: yarn install
      - run: yarn build
  test:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - run: yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build
