version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - checkout
      - run: yarn version
      - run:
          name: 'Print an ENV VAR Stored in the Project'
          command: echo ${MY_ENV_VAR}

workflows:
  build_only:
    jobs:
      - build:
          context: MY_ENV_VAR
