version: 2.1

orbs:
  node: circleci/node@5.0.2

executors:
  my-executor:
    docker:
      - image: cimg/node:18.4.0

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run: echo "Build start on `date`"
      - node/install-packages:
          check-cache: detect
      - run: yarn install
      - run: yarn build
  test:
    executor: my-executor
    steps:
      - run: echo "Test start on `date`"
      - run: yarn test

workflows:
  build_and_test:
    jobs:
      - need-approval:
          type: approval
          filters:
            branches:
              only:
                - beta
          type: approval
      - build:
          requires:
            - need-approval
      - test:
          requires:
            - build
